In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import json

In [31]:
import time
seed = np.random.randint(100)
np.random.seed(seed)
a = np.random.randint(5)
time.sleep(1)

bhc = []
cnt = 1

for i in range (1, 163):
    url = f'https://www.bhc.co.kr/location/map_sub.asp?cPage={i}&area=&gugubn=&search_text='
    info = {
        'Referer': 'https://www.bhc.co.kr/location/map.asp',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36'
    }
    res = requests.post(url, headers = info)
    html = BeautifulSoup(res.text, 'html.parser')
    
    print(f'{cnt}번째 크롤링 중입니다')
    cnt += 1
    
    
    for j in range(len(html.select('p.mt10'))):
        bhc.append(html.select('p.mt10')[j].text.strip())

1번째 크롤링 중입니다
2번째 크롤링 중입니다
3번째 크롤링 중입니다
4번째 크롤링 중입니다
5번째 크롤링 중입니다
6번째 크롤링 중입니다
7번째 크롤링 중입니다
8번째 크롤링 중입니다
9번째 크롤링 중입니다
10번째 크롤링 중입니다
11번째 크롤링 중입니다
12번째 크롤링 중입니다
13번째 크롤링 중입니다
14번째 크롤링 중입니다
15번째 크롤링 중입니다
16번째 크롤링 중입니다
17번째 크롤링 중입니다
18번째 크롤링 중입니다
19번째 크롤링 중입니다
20번째 크롤링 중입니다
21번째 크롤링 중입니다
22번째 크롤링 중입니다
23번째 크롤링 중입니다
24번째 크롤링 중입니다
25번째 크롤링 중입니다
26번째 크롤링 중입니다
27번째 크롤링 중입니다
28번째 크롤링 중입니다
29번째 크롤링 중입니다
30번째 크롤링 중입니다
31번째 크롤링 중입니다
32번째 크롤링 중입니다
33번째 크롤링 중입니다
34번째 크롤링 중입니다
35번째 크롤링 중입니다
36번째 크롤링 중입니다
37번째 크롤링 중입니다
38번째 크롤링 중입니다
39번째 크롤링 중입니다
40번째 크롤링 중입니다
41번째 크롤링 중입니다
42번째 크롤링 중입니다
43번째 크롤링 중입니다
44번째 크롤링 중입니다
45번째 크롤링 중입니다
46번째 크롤링 중입니다
47번째 크롤링 중입니다
48번째 크롤링 중입니다
49번째 크롤링 중입니다
50번째 크롤링 중입니다
51번째 크롤링 중입니다
52번째 크롤링 중입니다
53번째 크롤링 중입니다
54번째 크롤링 중입니다
55번째 크롤링 중입니다
56번째 크롤링 중입니다
57번째 크롤링 중입니다
58번째 크롤링 중입니다
59번째 크롤링 중입니다
60번째 크롤링 중입니다
61번째 크롤링 중입니다
62번째 크롤링 중입니다
63번째 크롤링 중입니다
64번째 크롤링 중입니다
65번째 크롤링 중입니다
66번째 크롤링 중입니다
67번째 크롤링 중입니다
68번째 크롤링 중입니다
69번째 크롤링 중입니다
70번째 크롤링 중입니다
71번째 크롤링 중입니다
72번째 크롤링 중입니다
73번째 크롤링 중입니다
74번째 크롤링 중입니다
75번째 크롤링 중입니다
76번째 크롤링 중입니다
77번째 크롤링 중입니다
78번째 크롤링 중입니다
79번째 크롤링 중입니다
80번째 크롤링 중입니다
81번째 크롤링 중입니다
82번째 크롤링 중입니다
83번째 크롤링 중입니다
84번째 크롤링 중입니다
85번째 크롤링 중입니다
86번째 크롤링 중입니다
87번째 크롤링 중입니다
88번째 크롤링 중입니다
89번째 크롤링 중입니다
90번째 크롤링 중입니다
91번째 크롤링 중입니다
92번째 크롤링 중입니다
93번째 크롤링 중입니다
94번째 크롤링 중입니다
95번째 크롤링 중입니다
96번째 크롤링 중입니다
97번째 크롤링 중입니다
98번째 크롤링 중입니다
99번째 크롤링 중입니다
100번째 크롤링 중입니다
101번째 크롤링 중입니다
102번째 크롤링 중입니다
103번째 크롤링 중입니다
104번째 크롤링 중입니다
105번째 크롤링 중입니다
106번째 크롤링 중입니다
107번째 크롤링 중입니다
108번째 크롤링 중입니다
109번째 크롤링 중입니다
110번째 크롤링 중입니다
111번째 크롤링 중입니다
112번째 크롤링 중입니다
113번째 크롤링 중입니다
114번째 크롤링 중입니다
115번째 크롤링 중입니다
116번째 크롤링 중입니다
117번째 크롤링 중입니다
118번째 크롤링 중입니다
119번째 크롤링 중입니다
120번째 크롤링 중입니다
121번째 크롤링 중입니다
122번째 크롤링 중입니다
123번째 크롤링 중입니다
124번째 크롤링 중입니다
125번째 크롤링 중입니다
126번째 크롤링 중입니다
127번째 크롤링 중입니다
128번째 크롤링 중입니다
129번째 크롤링 중입니다
130번째 크롤링 중입니다
131번째 크롤링 중입니다
132번째 크롤링 중입니다
133번째 크롤링 중입니다
134번째 크롤링 중입니다
135번째 크롤링 중입니다
136번째 크롤링 중입니다
137번째 크롤링 중입니다
138번째 크롤링 중입니다
139번째 크롤링 중입니다
140번째 크롤링 중입니다
141번째 크롤링 중입니다
142번째 크롤링 중입니다
143번째 크롤링 중입니다
144번째 크롤링 중입니다
145번째 크롤링 중입니다
146번째 크롤링 중입니다
147번째 크롤링 중입니다
148번째 크롤링 중입니다
149번째 크롤링 중입니다
150번째 크롤링 중입니다
151번째 크롤링 중입니다
152번째 크롤링 중입니다
153번째 크롤링 중입니다
154번째 크롤링 중입니다
155번째 크롤링 중입니다
156번째 크롤링 중입니다
157번째 크롤링 중입니다
158번째 크롤링 중입니다
159번째 크롤링 중입니다
160번째 크롤링 중입니다
161번째 크롤링 중입니다
162번째 크롤링 중입니다

In [65]:
bhc[0].split('\n')[0].split(':')[1]

' 경기 여주시 가남읍 태평로 24-1 (태평리) '

In [86]:
addr = []

for i in range(len(bhc)):
    addr.append(bhc[i].split('\n')[0].split(':')[1])
    
addr[0]

' 경기 여주시 가남읍 태평로 24-1 (태평리) '

In [87]:
new_bhc = []

for i in range(len(addr)):
    sp = []
    sp = addr[i].split()
    
    if sp[0] == '경기':
        sp[0] = '경기도'
        
    elif sp[0] == '경남':
        sp[0] = '경상남도'
        
    elif sp[0] == '경북':
        sp[0] = '경상북도'
        
    elif sp[0] == '충남':
        sp[0] = '충청남도'
        
    elif sp[0] == '충북':
        sp[0] = '충청북도'
        
    elif sp[0] == '전남':
        sp[0] = '전라남도'
        
    elif sp[0] == '전북':
        sp[0] = '전라북도'
        
    elif sp[0] == '인천':
        sp[0] = '인천광역시'
    
    elif sp[0] == '광주':
        sp[0] = '광주광역시'
    
    elif sp[0] == '대구':
        sp[0] = '대구광역시'
        
    elif sp[0] == '대전':
        sp[0] = '대전광역시'
        
    elif sp[0] == '부산':
        sp[0] = '부산광역시'
        
    elif sp[0] == '서울':
        sp[0] = '서울특별시'
        
    elif sp[0] == '울산':
        sp[0] = '울산광역시'
        
    elif sp[0] == '제주도':
        sp[0] = '제주특별자치도'
        
    elif sp[0] == '제주':
        sp[0] = '제주특별자치도'
        
    elif sp[0] == '세종':
        sp[0] = '세종특별자치시'    
        
    elif sp[0] == '세종시':
        sp[0] = '세종특별자치시'
        
        
        
        
        
        
##########################################################################        
        
        
    elif sp[1] == '한라대학로':
        sp[1] = '제주시'
    
    
    
    
        
    
    new_bhc.append(sp[0] + " " + sp[1])

In [88]:
new_bhc[0]

'경기도 여주시'

In [89]:
df = pd.DataFrame(new_bhc, columns=['addr'])

df['category'] = np.nan
df['brand'] = np.nan
df['category'] = df['category'].fillna('치킨')
df['brand'] = df['brand'].fillna('BHC')

df = df[['category', 'brand', 'addr']]
df

     category brand       addr
0          치킨   BHC    경기도 여주시
1          치킨   BHC   경기도 의정부시
2          치킨   BHC  서울특별시 송파구
3          치킨   BHC  서울특별시 금천구
4          치킨   BHC  서울특별시 강서구
...       ...   ...        ...
1615       치킨   BHC    경기도 부천시
1616       치킨   BHC    경기도 안성시
1617       치킨   BHC    경기도 파주시
1618       치킨   BHC   경상북도 포항시
1619       치킨   BHC    경기도 광명시

[1620 rows x 3 columns]

In [91]:
df.to_csv('bhc.csv', index = False)